import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createPacketDesk} from '../packet-server.mjs';
const bind=p=>({source_record_id:p.source_record_id,source_fingerprint:p.source_fingerprint,proposal_sha256:p.proposal_sha256,normalized_content_sha256:p.normalized_content_sha256});
async function start(t){const desk=createPacketDesk(),server=http.createServer(desk.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;const call=async(path='/api/state',body)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};return {call,desk};}
async function accepted(call,s){return (await call('/api/review',{expected_version:s.version,...bind(s.proposal),inspected:true})).data;}
test('Runtime only admits source packet and review never schedules/imports',async t=>{const {call}=await start(t),s=(await call()).data;assert.equal(s.counts.captures,15);assert.equal(s.counts.logical_rows,14);const a=await accepted(call,s);assert.equal(a.receipts.length,1);assert.equal(a.receipts[0].normalized_fields.next_due_date,null);assert.equal(a.receipts[0].normalized_fields.assigned_person,null);assert.equal(a.receipts[0].normalized_fields.target_import_status,'not_submitted');});
test('Repeated exact acceptance is idempotent',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),b=await accepted(call,a);assert.equal(b.receipts.length,1);assert.equal(a.receipts[0].receipt_sha256,b.receipts[0].receipt_sha256);});
test('Old client cannot accept regenerated proposal even with current version',async t=>{const {call}=await start(t),s=(await call()).data,n=(await call('/api/regenerate',{expected_version:s.version,...bind(s.proposal)})).data;const stale=await call('/api/review',{expected_version:n.version,...bind(s.proposal),inspected:true});assert.equal(stale.status,409);assert.equal(stale.data.error,'STALE_PROPOSAL');assert.equal(stale.data.state.receipts.length,0);});
test('New source revision invalidates receipt, typed trigger and asset scope',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),n=await call('/api/source-change',{expected_version:a.version,...bind(a.proposal),revision:'A-test-2',column:'site',value:'PLANT-B'});assert.equal(n.status,200);assert.equal(n.data.receipts[0].current,false);assert.equal(n.data.proposal.normalized_fields.site,'PLANT-B');assert.notEqual(n.data.proposal.source_fingerprint,a.proposal.source_fingerprint);assert.equal((await call('/api/review',{expected_version:n.data.version,...bind(a.proposal),inspected:true})).status,409);});
test('Frequency change never reuses acceptance or collapses a month to days',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),n=(await call('/api/source-change',{expected_version:a.version,...bind(a.proposal),revision:'A-test-2',column:'frequency_text',value:'매월'})).data;assert.equal(n.proposal.normalized_fields.frequency.unit,'month');assert.equal(n.receipts[0].current,false);assert.equal(n.proposal.normalized_fields.next_due_date,null);});
test('A missing field cannot be accepted by forged UI click',async t=>{const {call}=await start(t),s=(await call()).data,blocked=s.rows.find(r=>!r.reviewable),n=(await call('/api/open',{expected_version:s.version,source_record_id:blocked.source_record_id})).data;assert.equal((await call('/api/review',{expected_version:n.version,...bind(n.proposal),inspected:true})).status,400);});
test('Unsupported derived correction is rejected; return keeps originals immutable',async t=>{const {call}=await start(t),s=(await call()).data;const bad=await call('/api/correct',{expected_version:s.version,...bind(s.proposal),reason:'Bad conversion',normalized_fields:{...s.proposal.normalized_fields,frequency:{kind:'calendar_interval',value:30,unit:'day'}}});assert.equal(bad.status,400);const ret=(await call('/api/return',{expected_version:s.version,...bind(s.proposal),reason:'Clarify source wording'})).data;assert.deepEqual(ret.record,s.record);assert.equal(ret.proposal.proposal_revision,2);assert.equal(ret.returns[0].accepted,false);});
test('Export names exactly selected rows; no implicit omission and no import receipt',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),n=(await call('/api/select',{expected_version:a.version,source_record_ids:[a.opened]})).data;const exp=await call('/api/export',{expected_version:n.version,scope_sha256:n.export_preview.scope_sha256,source_record_ids:[n.opened]});assert.equal(exp.status,200);assert.equal(exp.data.download.row_count,1);assert.deepEqual(exp.data.download.source_record_ids,[n.opened]);assert.equal(exp.data.download.target_import_receipt,null);assert.equal(exp.data.export_acknowledgement.target_import_receipt,null);assert.match(exp.data.download.semantics,/No CMMS create, update, delete/);});
test('Filtering clears hidden selection and invalidates previous export scope',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),n=(await call('/api/select',{expected_version:a.version,source_record_ids:[a.opened]})).data,f=(await call('/api/filter',{expected_version:n.version,site:'PLANT-B'})).data;assert.equal(f.selected.length,0);assert.equal(f.export_preview.row_count,0);assert.equal((await call('/api/export',{expected_version:f.version,scope_sha256:n.export_preview.scope_sha256,source_record_ids:n.selected})).status,409);});
test('Including any unaccepted row blocks whole explicit export',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s),n=(await call('/api/select',{expected_version:a.version,source_record_ids:[a.opened,a.rows[1].source_record_id]})).data;assert.equal(n.export_preview.errors.length,1);assert.equal((await call('/api/export',{expected_version:n.version,scope_sha256:n.export_preview.scope_sha256,source_record_ids:n.selected})).status,400);});
test('Unknown/repeated/hidden selection is invalid input; oracle is not served',async t=>{const {call}=await start(t),s=(await call()).data;for(const ids of [['unknown'],[s.opened,s.opened]])assert.equal((await call('/api/select',{expected_version:s.version,source_record_ids:ids})).status,400);assert.equal((await call('/fixtures/original/maintenance-migration-fixtures-v1/evaluation/frozen-gold-v1.json')).status,404);});
test('Re-admitting identical historical bytes/revision cannot resurrect acceptance',async t=>{const {call}=await start(t);let s=(await call()).data;const change=async(revision,value)=>(await call('/api/source-change',{expected_version:s.version,...bind(s.proposal),revision,column:'frequency_text',value})).data;s=await change('B','매월');s=await accepted(call,s);const old=s.receipts[0];s=await change('C','매주');assert.equal(s.receipts[0].current,false);s=await change('B','매월');assert.equal(s.proposal.source_fingerprint,old.source_fingerprint);assert.notEqual(s.proposal.proposal_sha256,old.proposal_sha256);assert.equal(s.receipts[0].current,false);assert.equal(s.rows.find(r=>r.source_record_id===s.opened).review_state,'unreviewed');});
test('Accepted export retains exact lexical evidence and review timestamp; returns are explicit',async t=>{const {call}=await start(t),s=(await call()).data,a=await accepted(call,s);assert.deepEqual(a.receipts[0].evidence,s.proposal.evidence);assert.ok(a.receipts[0].reviewed_at);const n=(await call('/api/return',{expected_version:a.version,...bind(a.proposal),reason:'Please clarify source'})).data;assert.equal(n.proposal.review_state,'returned');assert.equal(n.receipts[0].current,false);});
