import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';import {createDesk} from '../server.mjs';
import {importSource} from '../source.mjs';
const row={row_id:'a',equipment_id:'00017',organization:'ORG',site:'A',task_text:'Review fictional register wording',frequency:'Monthly',responsible_role:'Planning reviewer'};
const raw=(rev='r1',change={})=>({source_id:'test',namespace:'test-only',source_revision:rev,format:'json',text:JSON.stringify({rows:[{...row,...change}]})});
async function start(t){const desk=createDesk([importSource(raw())]),server=http.createServer(desk.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const base='http://127.0.0.1:'+server.address().port;return async(path='/api/state',body)=>{const r=await fetch(base+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json()};};}
const review=s=>({expected_version:s.version,proposal_fingerprint:s.proposal.proposal_fingerprint,file_hash:s.proposal.file_hash,source_revision:s.proposal.source_revision,row_locator:s.proposal.row_locator,inspected:true});
test('Repeated inspection preserves a single immutable receipt',async t=>{const call=await start(t);const s=(await call()).data;const a=(await call('/api/review',review(s))).data;const b=(await call('/api/review',review(a))).data;assert.equal(b.receipts.length,1);assert.equal(a.receipts[0].receipt_fingerprint,b.receipts[0].receipt_fingerprint);});
test('Old client click cannot accept revised trigger or scope',async t=>{const call=await start(t),old=(await call()).data;const changed=await call('/api/source',{expected_version:old.version,source:raw('r2',{frequency:'500 operating hours',site:'B'})});assert.equal(changed.status,200);const stale=await call('/api/review',review(old));assert.equal(stale.status,409);assert.equal(stale.data.state.receipts.length,0);});
test('Exact displayed proposal binding rejects replacement even with fresh server version',async t=>{const call=await start(t),old=(await call()).data;const changed=(await call('/api/source',{expected_version:old.version,source:raw('r2',{frequency:'500 operating hours'})})).data;const stale=await call('/api/review',{...review(old),expected_version:changed.version});assert.equal(stale.status,409);assert.equal(stale.data.error,'STALE_PROPOSAL');});
test('Source change retains historical receipt and requires fresh review for export',async t=>{const call=await start(t),old=(await call()).data;const accepted=(await call('/api/review',review(old))).data;const changed=(await call('/api/source',{expected_version:accepted.version,source:raw('r2',{site:'B'})})).data;assert.equal(changed.sources.length,2);assert.equal(changed.receipts[0].current,false);assert.equal(changed.receipts[0].receipt_fingerprint,accepted.receipts[0].receipt_fingerprint);const exp=await call('/api/export',{expected_version:changed.version,proposal_fingerprint:old.proposal.proposal_fingerprint});assert.equal(exp.status,409);});
test('Same bytes with a new revision still invalidate old review',async t=>{const call=await start(t),s=(await call()).data;const a=(await call('/api/review',review(s))).data;const b=(await call('/api/source',{expected_version:a.version,source:raw('r2')})).data;assert.equal(b.receipts[0].current,false);assert.equal(b.proposal.source_revision,'r2');});
test('Empty new source revision has no proposal or current acceptance',async t=>{const call=await start(t),s=(await call()).data;const a=(await call('/api/review',review(s))).data;const b=(await call('/api/source',{expected_version:a.version,source:{...raw('r2'),text:'{"rows":[]}'}})).data;assert.equal(b.proposal,null);assert.equal(b.receipts[0].current,false);assert.equal((await call('/api/export',{expected_version:b.version,proposal_fingerprint:s.proposal.proposal_fingerprint})).status,409);});
test('Same revision differing row values retains both sources and blocks review',async t=>{const call=await start(t),s=(await call()).data;const changed=(await call('/api/source',{expected_version:s.version,source:raw('r1',{frequency:'500 operating hours'})})).data;assert.equal(changed.sources.filter(s=>s.admitted).length,2);assert.equal(changed.proposal.status,'CONFLICT');assert.equal((await call('/api/review',review(changed))).status,400);});
test('Local export acknowledgement is never a target import receipt',async t=>{const call=await start(t),s=(await call()).data;const a=(await call('/api/review',review(s))).data;const exp=await call('/api/export',{expected_version:a.version,proposal_fingerprint:a.proposal.proposal_fingerprint});assert.equal(exp.status,200);assert.equal(exp.data.export_acknowledgement.target_import_receipt,null);assert.equal(exp.data.download.draft_only,true);});
test('Split UTF-8 request chunks preserve original Korean source and hash',async t=>{
 const desk=createDesk([importSource(raw())]),server=http.createServer(desk.handler);await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));
 const input=raw('r2',{task_text:'Inspect 한글 fictional text'}),body=Buffer.from(JSON.stringify({expected_version:0,source:input}));const split=body.indexOf(Buffer.from('한'))+1;
 const result=await new Promise((resolve,reject)=>{const req=http.request({host:'127.0.0.1',port:server.address().port,path:'/api/source',method:'POST',headers:{'Content-Type':'application/json'}},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({status:res.statusCode,data:JSON.parse(Buffer.concat(chunks).toString('utf8'))}));});req.on('error',reject);req.write(body.subarray(0,split));setTimeout(()=>req.end(body.subarray(split)),20);});
 assert.equal(result.status,200);assert.equal(result.data.sources.at(-1).text,input.text);assert.equal(result.data.proposal.fields.task_text.value,'Inspect 한글 fictional text');
});
