import test from 'node:test';import assert from 'node:assert/strict';
import {createReferenceDesk} from '../ui/reference-layout/server.mjs';import {hash} from '../source.mjs';
const row={row_id:'local-1',equipment_id:'00017',organization:'SYNTHETIC-ORG',site:'SYNTHETIC-SITE',task_text:'<img src=x onerror=alert(1)> 한글 fictional review',frequency:'Monthly',responsible_role:'Planning reviewer'};
const input=(revision='r1',changes={})=>({source_id:'my-synthetic-source',namespace:'synthetic-local',source_revision:revision,format:'json',text:JSON.stringify({rows:[{...row,...changes}]})});
const review=s=>({expected_version:s.version,proposal_fingerprint:s.proposal.proposal_fingerprint,file_hash:s.proposal.file_hash,source_revision:s.proposal.source_revision,row_locator:s.proposal.row_locator,inspected:true});
async function start(t){const server=createReferenceDesk();await new Promise(r=>server.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>server.close(r)));const origin='http://127.0.0.1:'+server.address().port;return async(path='/source-desk/api/state',body)=>{const res=await fetch(origin+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});return {status:res.status,data:res.headers.get('Content-Type').includes('application/json')?await res.json():await res.text()};};}
test('default desk links to independent input and new admitted bytes complete review/export without changing packet',async t=>{
  const call=await start(t),packet=(await call('/api/state')).data;assert.match((await call('/')).data,/내 TSV\/JSON으로 초안 만들기/);assert.match((await call('/source-desk/')).data,/id="source-text"/);assert.equal((await call('/source-desk/source-app.mjs')).status,200);
  let s=(await call()).data;const original=structuredClone(s.sources[0]),source=input();s=(await call('/source-desk/api/source',{expected_version:s.version,source})).data;
  assert.equal(s.proposal.source_id,source.source_id);assert.equal(s.proposal.fields.equipment_id.value,'00017');assert.equal(s.proposal.fields.task_text.value,row.task_text);assert.equal(s.sources.at(-1).text,source.text);assert.equal(s.proposal.file_hash,hash(source.text));assert.deepEqual(s.sources[0],original);
  assert.equal((await call('/source-desk/api/review',{...review(s),inspected:false})).status,400);s=(await call('/source-desk/api/review',review(s))).data;
  const exp=await call('/source-desk/api/export',{expected_version:s.version,proposal_fingerprint:s.proposal.proposal_fingerprint});assert.equal(exp.status,200);assert.equal(exp.data.download.source.source_id,source.source_id);assert.equal(exp.data.download.asset.equipment_id,'00017');assert.equal(exp.data.download.task_text,row.task_text);assert.equal(exp.data.export_acknowledgement.target_import_receipt,null);assert.equal(exp.data.download.not_maintenance_authorization,true);
  const packetAfter=(await call('/api/state')).data;assert.equal(packetAfter.version,packet.version);assert.equal(packetAfter.counts.captures,15);assert.equal(packetAfter.receipts.length,0);
});
test('explicit revision retains original hash/receipt while stale review and export cannot revive',async t=>{
  const call=await start(t);let s=(await call()).data;s=(await call('/source-desk/api/source',{expected_version:s.version,source:input()})).data;const prior=s;s=(await call('/source-desk/api/review',review(s))).data;const receipt=structuredClone(s.receipts[0]);
  s=(await call('/source-desk/api/source',{expected_version:s.version,source:input('r2',{frequency:'500 operating hours'})})).data;assert.equal(s.proposal.source_revision,'r2');assert.equal(s.proposal.trigger.kind,'meter_interval');assert.equal(s.receipts[0].current,false);assert.equal(s.receipts[0].receipt_fingerprint,receipt.receipt_fingerprint);assert.equal(s.sources.find(x=>x.source_id==='my-synthetic-source'&&x.source_revision==='r1').file_hash,prior.proposal.file_hash);
  assert.equal((await call('/source-desk/api/review',review(prior))).status,409);const stale=await call('/source-desk/api/review',{...review(prior),expected_version:s.version});assert.equal(stale.status,409);assert.equal(stale.data.error,'STALE_PROPOSAL');assert.equal((await call('/source-desk/api/export',{expected_version:s.version,proposal_fingerprint:prior.proposal.proposal_fingerprint})).status,409);
  s=(await call('/source-desk/api/review',review(s))).data;assert.equal(s.receipts.length,2);assert.equal(s.receipts[1].current,true);
});
test('same-revision conflicts block even an earlier inspected source, invalid uploads preserve current state',async t=>{
  const call=await start(t);let s=(await call()).data;s=(await call('/source-desk/api/source',{expected_version:s.version,source:input()})).data;s=(await call('/source-desk/api/review',review(s))).data;s=(await call('/source-desk/api/source',{expected_version:s.version,source:input('r1',{frequency:'500 operating hours'})})).data;
  assert.equal(s.proposal.status,'CONFLICT');assert.equal(s.receipts[0].current,false);assert.equal((await call('/source-desk/api/review',review(s))).status,400);
  for(const source of [{...input(),format:'xlsx'},{...input(),source_id:'bad\nidentity'},{...input(),namespace:'a'.repeat(129)},{...input(),text:'x'.repeat(1024*1024+1)},{...input(),text:'{"rows":[{"equipment_id":17}]}'},{...input(),text:'{"rows":[],"rows":[]}'}])assert.equal((await call('/source-desk/api/source',{expected_version:s.version,source})).status,400);
  const after=(await call()).data;assert.equal(after.version,s.version);assert.deepEqual(after.sources,s.sources);
});
