import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {loadPacket,propose} from '../packet-core.mjs';import {createPacketDesk} from '../packet-server.mjs';
const packet=loadPacket(),r=packet.records[0],p=propose(r,packet.records),candidate={source_record_id:r.source_record_id,source_fingerprint:r.source_fingerprint,normalized_fields:p.normalized_fields,citations:{organization:'C4',site:'C5',asset_namespace:'C6',asset_id:'C7',task_text:'C8',frequency:'C9',responsible_role:'C10',last_recorded_date:'C11'},frequency_quote:r.values.frequency_text,blocking_issues:p.blocking_issues,scheduling_unknowns:p.scheduling_unknowns,reviewable:p.reviewable,review_state:'unreviewed'};
const attempt=(raw,status='complete',fp=r.source_fingerprint)=>({case_id:r.source_record_id,status,request:{messages:[{role:'user',content:JSON.stringify({case_id:r.source_record_id,source_fingerprint:fp,source_ref:r.source_ref})}]},raw:{message:{content:raw}}});
test('malformed/missing/cross-capture stored inputs leave deterministic fallback usable and raw hidden',()=>{for(const input of [null,[],{},false,{case_id:'',source_fingerprint:'old'},{case_id:'OTHER-CAPTURE',source_fingerprint:'old'}]){const a=attempt('OTHER RAW');a.request.messages[0].content=JSON.stringify(input);const s=createPacketDesk(packet,()=>a).snapshot();assert.equal(s.stored_model.status,'INVALID_STORED_INPUT');assert.equal(s.stored_model.candidate,null);assert.equal(Object.hasOwn(s.stored_model,'raw'),false);assert.deepEqual(s.proposal.normalized_fields,p.normalized_fields);}const a=attempt('OTHER RAW');a.case_id='OTHER';assert.equal(createPacketDesk(packet,()=>a).snapshot().stored_model.status,'INVALID_STORED_INPUT');});
test('Stored validated proposal never creates acceptance or inference',()=>{const s=createPacketDesk(packet,()=>attempt(JSON.stringify(candidate))).snapshot();assert.equal(s.stored_model.status,'VALIDATED_UNREVIEWED');assert.equal(s.receipts.length,0);assert.equal(s.experiment.model_calls,0);});
test('Invalid JSON, timeout and unsupported proposal remain separate from baseline',()=>{for(const [a,status]of [[attempt('{'),'INVALID_JSON'],[attempt('partial','failed-attempt'),'failed-attempt'],[attempt(JSON.stringify({...candidate,normalized_fields:{...p.normalized_fields,next_due_date:'tomorrow'}})),'REJECTED_BY_RULES']]){const s=createPacketDesk(packet,()=>a).snapshot();assert.equal(s.stored_model.status,status);assert.deepEqual(s.proposal.normalized_fields,p.normalized_fields);assert.equal(s.receipts.length,0);}});
test('Historical same-capture output retains original revision but loses candidate authority',()=>{const s=createPacketDesk(packet,()=>attempt(JSON.stringify(candidate),'complete','old')).snapshot();assert.equal(s.stored_model.status,'ARCHIVED_STALE');assert.equal(s.stored_model.candidate,null);assert.equal(s.stored_model.raw,JSON.stringify(candidate));assert.equal(s.stored_model.original_source_ref.source_revision,'A');assert.match(s.stored_model.meaning,/Historical/);});
test('An inaccessible current row supplies no cached model authority',async t=>{const desk=createPacketDesk(packet,()=>attempt(JSON.stringify(candidate))),server=http.createServer(desk.handler);await new Promise(res=>server.listen(0,'127.0.0.1',res));t.after(()=>new Promise(res=>server.close(res)));const s=desk.snapshot(),body={expected_version:s.version,source_record_id:r.source_record_id,source_fingerprint:r.source_fingerprint,proposal_sha256:s.proposal.proposal_sha256,normalized_content_sha256:p.normalized_content_sha256,revision:'not-in-scope',column:'site',value:'OTHER-SITE'};const response=await fetch('http://127.0.0.1:'+server.address().port+'/api/source-change',{method:'POST',body:JSON.stringify(body)}),n=await response.json();assert.notEqual(n.record.source_record_id,r.source_record_id);assert.ok(n.rows.some(x=>x.source_record_id===n.opened));assert.equal(n.stored_model.status,'INVALID_STORED_INPUT');assert.equal(n.stored_model.candidate,null);assert.equal(Object.hasOwn(n.stored_model,'raw'),false);assert.equal(n.rows.some(x=>x.source_record_id===r.source_record_id),false);});
