import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {createPacketDesk} from '../packet-server.mjs';
import {validationEvidence,exportDisplay,frequencySummary} from '../ui-evidence.mjs';
const bind=p=>({source_record_id:p.source_record_id,source_fingerprint:p.source_fingerprint,proposal_sha256:p.proposal_sha256,normalized_content_sha256:p.normalized_content_sha256});
async function start(t){const s=http.createServer(createPacketDesk().handler);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>s.close(r)));return async(path='/api/state',body)=>{const r=await fetch('http://127.0.0.1:'+s.address().port+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});assert.equal(r.status,200);return r.json();};}
async function downloaded(call){let s=await call();s=await call('/api/review',{expected_version:s.version,...bind(s.proposal),inspected:true});s=await call('/api/select',{expected_version:s.version,source_record_ids:[s.opened]});return {before:s,after:await call('/api/export',{expected_version:s.version,scope_sha256:s.export_preview.scope_sha256,source_record_ids:s.selected})};}
test('export acknowledgment freezes exact source/version/proposal bindings apart from current labels',async t=>{const call=await start(t),{before,after}=await downloaded(call),e=after.exports[0];assert.equal(e.snapshot_version,before.version);assert.deepEqual(e.source_record_ids,before.selected);assert.deepEqual(e.scope_rows[0].source_ref,before.record.source_ref);assert.equal(e.scope_rows[0].proposal_sha256,before.proposal.proposal_sha256);assert.equal(e.source_reviews_current,true);assert.equal(e.matches_current_selection,true);assert.equal(e.target_import_receipt,null);assert.equal(after.download.target_import_status,'not_submitted');});
test('filter selection change preserves downloaded source snapshot but does not authorize current export',async t=>{const call=await start(t),{after}=await downloaded(call),s=await call('/api/filter',{expected_version:after.version,site:'PLANT-B'});assert.equal(s.exports[0].source_reviews_current,true);assert.equal(s.exports[0].matches_current_selection,false);assert.deepEqual(s.exports[0].scope_rows,after.exports[0].scope_rows);assert.equal(s.export_preview.row_count,0);assert.match(exportDisplay(s.exports[0]).selection,/Different/);});
test('source or proposal change marks old download historical without altering its exact evidence',async t=>{for(const action of ['source-change','regenerate']){const call=await start(t),{after}=await downloaded(call),s=await call('/api/'+action,{expected_version:after.version,...bind(after.proposal),revision:'CPU-NEW',column:'frequency_text',value:'매월'});assert.equal(s.exports[0].source_reviews_current,false);assert.equal(s.exports[0].matches_current_selection,false);assert.deepEqual(s.exports[0].scope_rows,after.exports[0].scope_rows);assert.equal(s.receipts[0].current,false);assert.match(exportDisplay(s.exports[0]).label,/Historical/);assert.equal(s.export_preview.errors.length,1);}});
test('filtered source change reconciles opened and selected IDs to visible set, preserving history',async t=>{const call=await start(t);let s=await call();s=await call('/api/filter',{expected_version:s.version,site:'PLANT-A'});s=await call('/api/review',{expected_version:s.version,...bind(s.proposal),inspected:true});s=await call('/api/select',{expected_version:s.version,source_record_ids:[s.opened]});const changed=s.opened;s=await call('/api/source-change',{expected_version:s.version,...bind(s.proposal),revision:'CPU-SITE-B',column:'site',value:'PLANT-B'});const ids=s.rows.map(r=>r.source_record_id);assert.ok(s.opened===null||ids.includes(s.opened));assert.ok(s.selected.every(id=>ids.includes(id)));assert.ok(!s.selected.includes(changed));assert.notEqual(s.opened,changed);assert.equal(s.receipts[0].current,false);assert.equal(s.export_preview.row_count,0);});
test('field-specific rejection retains raw values and bounded comparison; no repaired model credit',()=>{const expected={frequency:{kind:'calendar_interval',value:1,unit:'month'},asset_id:'00017'},actual={...expected,frequency:{kind:'calendar_interval',value:30,unit:'day'}};const stored={candidate:{normalized_fields:actual},validation:{errors:['UNSUPPORTED_NORMALIZED_FIELDS','UNSUPPORTED_BLOCKERS','INVALID_REVIEW_BOUNDARY','INVALID_CITATION_asset_id']}};const rows=validationEvidence(stored,{normalized_fields:expected,blocking_issues:['missing_role']});assert.equal(rows[0].field,'frequency');assert.deepEqual(rows[0].actual,actual.frequency);assert.match(rows[0].explanation,/not general semantic/);assert.equal(rows[1].category,'Authoritative backend decision');assert.equal(rows[2].category,'Authority boundary');assert.equal(rows[3].field,'asset_id');assert.deepEqual(actual.frequency,{kind:'calendar_interval',value:30,unit:'day'});});
test('missing validation is unavailable; empty errors remain unreviewed; schema error never semantic credit',()=>{assert.equal(validationEvidence({status:'ARCHIVED_STALE'},null)[0].category,'Availability');assert.equal(validationEvidence({validation:{errors:[]}},null)[0].code,'VALIDATED_UNREVIEWED');assert.equal(validationEvidence({validation:{errors:['INVALID_SCHEMA']}},null)[0].category,'Structure');});
test('readable summary preserves unresolved combinations/events and runtime/calendar distinction',()=>{assert.match(frequencySummary({kind:'calendar_interval',value:1,unit:'month'}),/calendar month/);assert.match(frequencySummary({kind:'meter_interval',value:500}),/operating-runtime/);assert.match(frequencySummary({kind:'combined',relation:null,triggers:[]}),/unspecified/);assert.doesNotMatch(frequencySummary({kind:'combined',relation:null,triggers:[]}),/whichever-first/);assert.match(frequencySummary({kind:'event_trigger',event:null}),/clarification/);});
