import test from 'node:test';import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync,mkdirSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join,dirname} from 'node:path';import {pathToFileURL} from 'node:url';
import {sha256} from '../packet-core.mjs';
import {V2_POLICY,V2_SCHEMA,validateV2Shape,validateV2Evidence,v2SuggestionState,typedFrequencyShape} from '../development/v2-contract.mjs';
import {developmentInput} from '../development/v2-input.mjs';
import {gradeV2} from '../development/v2-grade.mjs';
import {enrichV2} from '../development/v2-backend.mjs';
import {parseV2JSON} from '../development/v2-json.mjs';
import {developmentDeskCase,createDevelopmentDesk} from '../development/v2-desk.mjs';
import {V2_FROZEN_FILES,verifyV2Freeze,verifyV2Attempt} from '../development/v2-integrity.mjs';
const frequency={kind:'calendar_interval',value:1,unit:'month'};
function record(quote='한 달에 한 번'){return {source_record_id:'PARAPHRASE-CPU',source_fingerprint:'a'.repeat(64),logical_record_identity:{revision:'1'},content_comparison_columns:['frequency_text'],values:{frequency_text:quote,organization:'ORG',site:'SITE',asset_namespace:'FIXTION',asset_id:'00017',task_text:'Fictional planning review',responsible_role:'reviewer',last_recorded_date:''},cells:[{cell_column:'frequency_text',quote,lexical_span:{byte_start_0_based:12,byte_end_exclusive:31}}]};}
function proposal(r=record(),f=frequency){return {source_record_id:r.source_record_id,source_fingerprint:r.source_fingerprint,evidence:{cell_id:'C9',quote:r.values.frequency_text,span:{start:12,end:31}},decision:'propose',frequency:structuredClone(f)};}
const label=(r=record())=>({case_id:r.source_record_id,expected_decision:'propose',frequency,acceptable_frequencies:[]});
const attempt=v=>({case_id:v.source_record_id,status:'complete',raw:{done:true,done_reason:'stop',message:{content:JSON.stringify(v)}}});
test('novel paraphrase structurally valid without exact grammar; independent author labels supply meaning',()=>{
  const r=record(),p=proposal(r);assert.equal(validateV2Evidence(p,r),true);assert.equal(v2SuggestionState(p,r),'STRUCTURALLY_VALID_REQUIRES_SEMANTIC_REVIEW');
  const score=gradeV2([r],[attempt(p)],[label(r)]);assert.equal(score.metrics.frequency.correct,1);assert.equal(score.metrics.frequency_fields.correct,3);
  const wrong=proposal(r,{...frequency,value:30,unit:'day'});assert.equal(validateV2Evidence(wrong,r),true);assert.equal(gradeV2([r],[attempt(wrong)],[label(r)]).metrics.frequency.correct,0);
});
test('source fingerprint and exact lexical span remain independent safety requirements',()=>{const r=record(),p=proposal(r);p.evidence.span.end++;assert.equal(validateV2Shape(p),true);assert.equal(validateV2Evidence(p,r),false);assert.equal(v2SuggestionState(p,r),'INVALID_SOURCE_BINDING');p.evidence.span.end--;p.source_fingerprint='b'.repeat(64);assert.equal(validateV2Evidence(p,r),false);});
test('empty objects, numeric strings, null proposal and authority fields rejected',()=>{const p=proposal();for(const value of [{},{...p,frequency:{}},{...p,frequency:null},{...p,frequency:{...frequency,value:'1'}},{...p,reviewable:true}])assert.equal(validateV2Shape(value),false);});
test('integer precision/tuple ordering and explicit runtime basis enforced',()=>{assert.equal(typedFrequencyShape({kind:'meter_interval',value:500,unit:'hour',basis:'operating_runtime'}),true);assert.equal(typedFrequencyShape({...frequency,value:1.5}),false);assert.equal(typedFrequencyShape({...frequency,value:Number.MAX_SAFE_INTEGER+1}),false);const meter={kind:'meter_interval',value:500,unit:'hour',basis:'operating_runtime'};assert.equal(typedFrequencyShape({kind:'combined',relation:'whichever_first',triggers:[frequency,meter]}),true);assert.equal(typedFrequencyShape({kind:'combined',relation:'whichever_first',triggers:[meter,frequency]}),false);});
test('event source must be full verbatim quote while its semantics remain human reviewed',()=>{const r=record('When fictional inspection status changes'),p=proposal(r,{kind:'event_trigger',event:r.values.frequency_text});assert.equal(validateV2Evidence(p,r),true);p.frequency.event='made-up event';assert.equal(validateV2Shape(p),true);assert.equal(validateV2Evidence(p,r),false);});
test('explicit abstention graded against independent reason; denominator zero is null',()=>{const r=record('as needed'),p={...proposal(r),decision:'abstain',frequency:null,reason:'unspecified_event'};assert.equal(v2SuggestionState(p,r),'ABSTENTION_REQUIRES_SEMANTIC_REVIEW');const score=gradeV2([r],[attempt(p)],[{case_id:r.source_record_id,expected_decision:'abstain',frequency:null,acceptable_reasons:['unspecified_event']}]);assert.equal(score.metrics.required_abstention_reason.correct,1);assert.equal(score.metrics.frequency.rate,null);assert.equal(score.metrics.frequency_fields.rate,null);});
test('incomplete, failed, not-attempted and invalid JSON remain denominators; no coercion',()=>{const r=record();for(const attempts of [[],[{case_id:r.source_record_id,status:'failed-attempt'}],[{...attempt(proposal(r)),status:'incomplete-output'}],[{...attempt(proposal(r)),raw:{done:true,message:{content:'{} nope'}}}]]){const score=gradeV2([r],attempts,[label(r)]);assert.equal(score.metrics.frequency.total,1);assert.equal(score.metrics.frequency.correct,0);assert.equal(score.development_criterion_met,false);}});
test('label mismatch rejects; raw authority fields separately counted',()=>{const r=record();assert.throws(()=>gradeV2([r],[],[]),/case_set/);const p={...proposal(r),reviewable:true};const s=gradeV2([r],[attempt(p)],[label(r)]);assert.equal(s.metrics.unsafe_authority_field_count,1);assert.equal(s.metrics.frequency.correct,0);});
test('listed equivalents are full semantic matches; canonical leaf metrics remain distinct',()=>{const r=record(),p=proposal(r,{kind:'calendar_interval',value:12,unit:'month'}),l={...label(r),frequency:{kind:'calendar_interval',value:1,unit:'year'},acceptable_frequencies:[p.frequency]};const s=gradeV2([r],[attempt(p)],[l]);assert.equal(s.metrics.frequency.correct,1);assert.equal(s.metrics.frequency_fields.correct,1);});
test('backend never frequency-repairs or gives semantic acceptance; novel source has no parser veto',()=>{const r=record(),p=proposal(r);const b=enrichV2(r,[r],p);assert.deepEqual(b.authoritative_source_blockers,[]);assert.equal(b.literal_fields.asset_id,'00017');assert.equal(Object.hasOwn(b,'frequency'),false);assert.equal(b.target_import_status,'not_submitted');assert.equal(b.next_due_date,null);assert.match(b.semantic_review,/required/);});
test('backend missing identity/conflict/formula source blockers independent from meaning',()=>{const r=record();r.values.asset_id='';r.values.task_text='=INERT()';const second=structuredClone(r);second.values.frequency_text='different';const b=enrichV2(r,[r,second],proposal(r));assert.ok(b.authoritative_source_blockers.includes('missing_asset_id'));assert.ok(b.authoritative_source_blockers.includes('formula_like_task'));assert.ok(b.authoritative_source_blockers.includes('same_identity_content_conflict'));});
test('strict content JSON rejects duplicate escaped/member names and fences',()=>{assert.throws(()=>parseV2JSON('{"x":1,"\\u0078":2}'),/duplicate/);assert.throws(()=>parseV2JSON('{"nested":{"x":1,"x":2}}'),/duplicate/);assert.throws(()=>parseV2JSON('```json {} ```'));assert.deepEqual(parseV2JSON('[{"x":1},{"x":2}]'),[{x:1},{x:2}]);});
test('initial development input precisely three original dev records; no labels or enriched answers',()=>{const input=developmentInput();assert.deepEqual(input.cases.map(c=>c.source_record_id),['PM001','PM002','PM010']);for(const c of input.cases){assert.equal(Object.hasOwn(c,'frequency'),false);assert.equal(Object.hasOwn(c,'blockers'),false);assert.equal(c.evidence.cell_id,'C9');}assert.equal(V2_POLICY.max_http_calls,3);assert.equal(V2_POLICY.retries,0);assert.equal(V2_POLICY.v1_evaluation_reuse,false);});
test('generated schema exactly matches frozen source and strict draft07 definitions',()=>{assert.deepEqual(JSON.parse(readFileSync(new URL('../development/v2-frequency-schema.json',import.meta.url),'utf8')),V2_SCHEMA);assert.equal(V2_SCHEMA.definitions.combined.properties.triggers.additionalItems,false);});
test('versioned development desk cannot access evaluation IDs or invoke model',async()=>{
  assert.throws(()=>developmentDeskCase('PM003'),/not_allowed/);assert.equal(developmentDeskCase('PM001').model_calls_from_ui,0);
  const server=createDevelopmentDesk();await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  try{const origin='http://127.0.0.1:'+server.address().port;assert.equal((await fetch(origin+'/api/infer',{method:'POST'})).status,405);assert.equal((await fetch(origin+'/api/case?id=PM003')).status,400);assert.match(await(await fetch(origin+'/')).text(),/semantic meaning/);}finally{await new Promise(resolve=>server.close(resolve));}
});
test('complete fixed freeze rejects truncated maps and post-freeze label changes',()=>{
  const directory=mkdtempSync(join(tmpdir(),'p09-v2-cpu-')),root=pathToFileURL(directory+'/');
  try{
    for(const name of V2_FROZEN_FILES){mkdirSync(dirname(join(directory,name)),{recursive:true});writeFileSync(join(directory,name),'CPU fixture');}
    const file=join(directory,'artifacts/v2-development/freeze.json'),freeze={experiment_frozen:true,version:V2_POLICY.version,phase:'development',declared_commit:'a'.repeat(40),model_calls_at_freeze:0,allowed_case_ids:V2_POLICY.allowed_case_ids,file_digests:Object.fromEntries(V2_FROZEN_FILES.map(n=>[n,sha256('CPU fixture')]))};
    writeFileSync(file,JSON.stringify(freeze));assert.equal(verifyV2Freeze(root).freeze.declared_commit,freeze.declared_commit);
    writeFileSync(join(directory,'development/labels/original-development.json'),'changed label');assert.throws(()=>verifyV2Freeze(root),/frozen_source_changed/);
    writeFileSync(file,JSON.stringify({...freeze,file_digests:{}}));assert.throws(()=>verifyV2Freeze(root),/incomplete_freeze/);
  }finally{rmSync(directory,{recursive:true,force:true});}
});
test('attempt request and exact freeze provenance bind scoring',()=>{
  const source=developmentInput(),c=source.cases[0],frozen={freeze:{declared_commit:'a'.repeat(40)},digest:'b'.repeat(64)},prompt='CPU',schema=V2_SCHEMA;
  const request={model:V2_POLICY.model,messages:[{role:'system',content:prompt+'\n\nExact response JSON Schema:\n'+JSON.stringify(schema)},{role:'user',content:JSON.stringify(c)}],format:schema,stream:false,think:false,truncate:false,shift:false,keep_alive:'30s',options:{num_ctx:4096,num_predict:640,temperature:0,seed:42}};
  const a={case_id:c.source_record_id,version:V2_POLICY.version,phase:'development',declared_commit:frozen.freeze.declared_commit,freeze_digest:frozen.digest,retry_calls:0,demo_calls:0,request};
  assert.doesNotThrow(()=>verifyV2Attempt(a,source,frozen,prompt,schema));assert.throws(()=>verifyV2Attempt({...a,freeze_digest:'old'},source,frozen,prompt,schema),/provenance/);a.request.options.num_predict=999;assert.throws(()=>verifyV2Attempt(a,source,frozen,prompt,schema),/request/);
});
test('nested authority fields count independently from invalid shape',()=>{const r=record(),p=proposal(r);p.frequency.accepted=true;const s=gradeV2([r],[attempt(p)],[label(r)]);assert.equal(s.metrics.shape.correct,0);assert.equal(s.metrics.unsafe_authority_field_count,1);});
