let state=null,tail=Promise.resolve(),busy=false;const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function controls(){for(const node of document.querySelectorAll('button,input,select,textarea'))node.disabled=busy;const p=state?.proposal;$('review').disabled=busy||!p||p.status==='CONFLICT'||!$('inspected').checked;$('export').disabled=busy||!state?.receipts.some(r=>r.current);}
function render(next){if(state&&next.version<state.version)return;const old=state?.proposal?.proposal_fingerprint;state=next;const p=state.proposal;if(old!==p?.proposal_fingerprint)$('inspected').checked=false;
  $('row-select').innerHTML=state.rows.map(r=>`<option value="${esc(r.key)}" ${r.key===state.selected?'selected':''}>${esc(r.row_id||'[missing row ID]')} · ${esc(r.equipment_id||'[missing asset]')} · ${esc(r.site||'[missing site]')}</option>`).join('');
  const source=state.sources.find(s=>s.file_hash===p?.file_hash&&s.source_id===p?.source_id&&s.namespace===p?.namespace&&s.source_revision===p?.source_revision);
  if(!p||!source){
    const empty=state.sources.find(s=>s.admitted);$('source-status').textContent=empty?empty.source_id+' · '+empty.source_revision:'No admitted source';$('source-grid').innerHTML='<tbody><tr><td>No current planning rows. No old values are inherited.</td></tr></tbody>';$('source-meta').textContent=empty?'SHA256 '+empty.file_hash:'';$('original-source').textContent=empty?.text??'';$('cell-detail').textContent='';$('proposal-status').textContent='NO_CURRENT_PLANNING_ROW';$('field-diff').innerHTML='';$('trigger').textContent='null';$('rule').textContent='No row to normalize';$('unresolved').innerHTML='<li>No current planning row; clarification or a new source is required.</li>';$('conflicts').textContent='';$('binding').textContent='No current proposal';$('receipt').textContent='No current review receipt.';$('history').innerHTML=state.receipts.map(r=>`<div class="receipt-card historical"><strong>Historical review</strong> · ${esc(r.source_revision)}<p>${esc(r.receipt_fingerprint)}</p></div>`).join('');$('experiment').textContent=state.experiment.status+' · model calls '+state.experiment.model_calls+' · evaluation not run';controls();return;
  }
  const headers=[...new Set(source.rows.flatMap(r=>Object.keys(r.cells)))];
  $('source-grid').innerHTML='<thead><tr><th>Locator</th>'+headers.map(h=>`<th>${esc(h)}</th>`).join('')+'</tr></thead><tbody>'+source.rows.map(r=>r.section_break?`<tr class="section-break"><td colspan="${headers.length+1}">${esc(r.locator)} · section break / no inherited values</td></tr>`:`<tr class="${r.locator===p.row_locator?'selected':''}"><th>${esc(r.locator)}</th>`+headers.map(h=>{const c=r.cells[h];return `<td>${c?`<button data-cell="${esc(c.locator)}">${c.value?esc(c.value):'<span class="blank">[blank]</span>'}</button>`:'<span class="blank">[missing cell]</span>'}</td>`;}).join('')+'</tr>').join('')+'</tbody>';
  $('source-status').textContent=source.source_id+' · '+source.source_revision;$('source-meta').textContent='Namespace '+source.namespace+' · SHA256 '+source.file_hash+' · original UTF-8 text, no formula execution';$('original-source').textContent=source.text;
  for(const button of $('source-grid').querySelectorAll('button'))button.onclick=()=>{const c=source.rows.flatMap(r=>Object.values(r.cells)).find(c=>c.locator===button.dataset.cell);$('cell-detail').textContent=c.locator+' · UTF-16 ['+c.span.start+','+c.span.end+') · UTF-8 bytes ['+c.span.utf8_start+','+c.span.utf8_end+') · exact raw span: '+JSON.stringify(c.span.raw);$('original-source').parentElement.open=true;$('original-source').focus();};
  $('proposal-status').textContent=p.status;$('field-diff').innerHTML='<thead><tr><th>Field</th><th>Original cell value</th><th>Proposed value</th><th>Rule / source locator</th></tr></thead><tbody>'+Object.entries(p.fields).map(([name,f])=>`<tr><th>${esc(name)}</th><td>${f.value===null?'[missing cell]':f.value===''?'[blank]':esc(f.value)}</td><td>${f.value===null?'unresolved':f.value===''?'unresolved':esc(f.value)}</td><td>${esc(f.normalization_rule)}<br>${f.source_cells.map(c=>esc(c.locator)).join(', ')}</td></tr>`).join('')+'</tbody>';
  $('trigger').textContent=JSON.stringify(p.trigger,null,2)??'null';$('rule').textContent='Frequency rule: '+p.normalization_rule+' · monthly is calendar months; operating hours are a meter.';$('unresolved').innerHTML=p.unresolved.length?p.unresolved.map(x=>`<li>${esc(x)} — clarification required, no invented value</li>`).join(''):'<li>No missing field detected by these bounded rules. Human inspection still required.</li>';$('conflicts').textContent=p.conflicts.length?'Same namespace / row ID / revision has conflicting values. No draft acceptance or last-write-wins merge.':'';
  $('binding').textContent='Proposal SHA256 '+p.proposal_fingerprint+' · exact source hash, revision, cells, trigger and unresolved fields bound.';
  const receipt=state.receipts.find(r=>r.current);$('receipt').innerHTML=receipt?`<div class="receipt-card"><strong>${esc(receipt.draft.status)}</strong><p>${esc(receipt.receipt_id)} · ${esc(receipt.receipt_fingerprint)}</p><p>Local source-bound draft review. Role label is not a named person or authorization.</p></div>`:'<p>No current review receipt.</p>';
  $('history').innerHTML=state.receipts.length?state.receipts.map(r=>`<div class="receipt-card ${r.current?'':'historical'}"><strong>${r.current?'Current displayed draft':'Historical review'}</strong> · ${esc(r.row_locator)} · ${esc(r.source_revision)}<p>${esc(r.receipt_fingerprint)}</p></div>`).join(''):'<p>No previous inspections.</p>';
  $('experiment').textContent=state.experiment.status+' · model calls '+state.experiment.model_calls+' · evaluation not run';controls();
}
function request(path,body){const job=async()=>{busy=true;controls();try{const payload=body?{...body,expected_version:state.version}:null;const response=await fetch(path,{method:payload?'POST':'GET',headers:payload?{'Content-Type':'application/json'}:{},body:payload?JSON.stringify(payload):undefined});const result=await response.json();if(result.state)render(result.state);else if(result.sources)render(result);if(!response.ok){$('inspected').checked=false;$('message').textContent=result.message??result.error;return null;}$('message').textContent='';return result;}catch(error){$('message').textContent='Request unavailable: '+error.message;return null;}finally{busy=false;controls();}};const result=tail.then(job,job);tail=result.catch(()=>{});return result;}
$('refresh').onclick=()=>request('/api/state');$('row-select').onchange=()=>request('/api/select',{key:$('row-select').value});$('inspected').onchange=controls;
$('review').onclick=()=>{const p=state.proposal;request('/api/review',{proposal_fingerprint:p.proposal_fingerprint,file_hash:p.file_hash,source_revision:p.source_revision,row_locator:p.row_locator,inspected:$('inspected').checked});};
$('export').onclick=async()=>{const result=await request('/api/export',{proposal_fingerprint:state.proposal.proposal_fingerprint});if(!result?.download)return;const blob=new Blob([JSON.stringify({draft:result.download,local_export_acknowledgement:result.export_acknowledgement},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reviewed-fictional-job-plan-draft.json';a.click();URL.revokeObjectURL(url);};
$('import-form').onsubmit=event=>{event.preventDefault();request('/api/source',{source:Object.fromEntries(new FormData(event.target))});};
request('/api/state');
