import {validationEvidence,exportDisplay,frequencySummary} from './ui-evidence.mjs';
let state=null,tail=Promise.resolve(),busy=false,focusGeneration=0;
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.addEventListener('focusin',()=>focusGeneration++);
const binding=()=>{const p=state.proposal;return {source_record_id:p.source_record_id,source_fingerprint:p.source_fingerprint,proposal_sha256:p.proposal_sha256,normalized_content_sha256:p.normalized_content_sha256};};
const canonical=v=>v===null||typeof v!=='object'?JSON.stringify(v):Array.isArray(v)?'['+v.map(canonical).join(',')+']':'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+canonical(v[k])).join(',')+'}';
function editorMatches(){try{return !!state?.proposal&&canonical(JSON.parse($('correction').value))===canonical(state.proposal.normalized_fields);}catch{return false;}}
function controls(){for(const n of document.querySelectorAll('button,input,select,textarea'))n.disabled=busy;const p=state?.proposal;for(const id of ['regenerate','return','correct','source-change','inspected'])$(id).disabled=busy||!p;$('review').disabled=busy||!p?.reviewable||!editorMatches()||!$('inspected').checked;$('export').disabled=busy||!state?.export_preview.row_count||!!state?.export_preview.errors.length;$('inspect-model').disabled=busy||!p||!['VALIDATED_UNREVIEWED','REJECTED_BY_RULES'].includes(state?.stored_model.status)||!state?.stored_model.candidate?.normalized_fields;$('restore-rule').disabled=busy||!p;}
function render(next){if(state&&next.version<state.version)return;const old=state?.proposal?.proposal_sha256;state=next;const p=state.proposal,r=state.record;if(old!==p?.proposal_sha256)$('inspected').checked=false;
  $('source-heading').textContent=r?`Current capture ${r.source_record_id} · revision ${r.source_ref.source_revision} · admitted revisions: ${state.admitted_source_revisions.join(', ')}`:'No current visible capture';
  $('frequency-summary').textContent=frequencySummary(p?.normalized_fields.frequency);
  $('site').value=state.filter_site;$('counts').textContent=`${state.counts.visible} visible captures / ${state.counts.captures} admitted captures / ${state.counts.logical_rows} logical rows`;
  const cols=['row_key','organization','site','asset_namespace','asset_id','task_text','frequency_text','responsible_role'];
  $('source-grid').innerHTML='<thead><tr><th>Export selection</th><th>Open capture</th>'+cols.map(c=>`<th>${esc(c)}</th>`).join('')+'<th>Review</th></tr></thead><tbody>'+state.rows.map(row=>`<tr class="${row.source_record_id===state.opened?'selected':''}"><td><input type="checkbox" aria-label="Select ${esc(row.source_record_id)} for export" data-select="${esc(row.source_record_id)}" ${state.selected.includes(row.source_record_id)?'checked':''}></td><td><button data-open="${esc(row.source_record_id)}">${esc(row.source_record_id)}</button></td>`+cols.map(c=>`<td>${row[c]?esc(row[c]):'<span class="blank">[blank; not inherited]</span>'}</td>`).join('')+`<td>${esc(row.review_state)}<br>${row.reviewable?'normalization eligible':'blocked'}</td></tr>`).join('')+'</tbody>';
  for(const b of document.querySelectorAll('[data-open]'))b.onclick=()=>action('/api/open',{source_record_id:b.dataset.open},{selector:`[data-open="${b.dataset.open}"]`});
  for(const b of document.querySelectorAll('[data-select]'))b.onchange=()=>action('/api/select',{source_record_ids:b.checked?[...state.selected,b.dataset.select]:state.selected.filter(id=>id!==b.dataset.select)},{selector:`[data-select="${b.dataset.select}"]`});
  if(old!==p?.proposal_sha256){$('cell-detail').textContent='Open an evidence cell to inspect its exact source pointer.';if(!$('cell-detail').parentElement.contains(document.activeElement))$('cell-detail').parentElement.open=false;}
  $('opened-title').textContent=(r?.source_record_id??'No visible row')+' · source / normalized comparison';$('proposal-status').textContent=p?(state.receipts.some(x=>x.current&&x.proposal_sha256===p.proposal_sha256)?'ACCEPTED NORMALIZATION':p.review_state==='returned'?'RETURNED FOR CLARIFICATION':p.reviewable?'NORMALIZATION ELIGIBLE':'BLOCKED'):'NO_CURRENT_ROW';
  $('source-meta').textContent=r?`${r.source_ref.file} / ${r.source_ref.sheet_name} / TSV line ${r.source_ref.tsv_line_1_based} / revision ${r.source_ref.source_revision} · file SHA256 ${r.source_ref.file_sha256}`:'';
  const fields=p?Object.keys(p.normalized_fields):[];
  $('field-diff').innerHTML='<thead><tr><th>Normalized field</th><th>Exact source cell</th><th>Derived value</th><th>Mapping / validation</th></tr></thead><tbody>'+fields.map(f=>{const c=r.cells.find(c=>c.cell_column===(f==='frequency'?'frequency_text':f));return `<tr><th>${esc(f)}</th><td>${c?`<button data-cell="${esc(c.cell_column)}">${esc(c.quote||'[blank]')}</button><p>${esc(c.file)} : ${c.tsv_line_1_based} / ${esc(c.cell_column)} · bytes [${c.lexical_span.byte_start_0_based},${c.lexical_span.byte_end_exclusive})</p>`:'No source assignment'}</td><td>${esc(JSON.stringify(p.normalized_fields[f]))}</td><td>${f==='frequency'?esc(p.normalizer_rule_version):c?'Literal cell preserved':'Fixed draft invariant'}${c?'<br>Exact source pointer validated':''}</td></tr>`;}).join('')+'</tbody>';
  for(const b of document.querySelectorAll('[data-cell]'))b.onclick=()=>{const c=r.cells.find(c=>c.cell_column===b.dataset.cell);$('cell-detail').textContent=JSON.stringify(c,null,2);$('cell-detail').parentElement.open=true;$('cell-detail').focus();};
  $('trigger').textContent=JSON.stringify(p?.normalized_fields.frequency??null,null,2);$('blockers').innerHTML=(p?.blocking_issues.length?p.blocking_issues:['None; explicit inspection is still required']).map(x=>`<li>${esc(x)}</li>`).join('');$('unknowns').innerHTML=(p?.scheduling_unknowns??[]).map(x=>`<li>${esc(x)}</li>`).join('');
  $('binding').textContent=p?`Source ${p.source_fingerprint} · proposal r${p.proposal_revision} ${p.proposal_sha256} · normalized content ${p.normalized_content_sha256}`:'';if(old!==p?.proposal_sha256)$('correction').value=JSON.stringify(p?.normalized_fields??{},null,2);
  const current=state.receipts.find(x=>x.current&&x.proposal_sha256===p?.proposal_sha256);$('receipt').textContent=current?`${current.receipt_id} · current accepted normalization · unscheduled / not_submitted`:'No current acceptance for this displayed proposal.';
  $('export-count').textContent=state.export_preview.row_count+' selected rows';$('export-rows').textContent='Exact capture IDs: '+(state.selected.join(', ')||'none');$('export-preview').textContent=JSON.stringify(state.export_preview,null,2);
  $('export-history').innerHTML=state.exports.length?state.exports.map(e=>{const d=exportDisplay(e);return `<article class="receipt-card ${e.source_reviews_current?'':'historical'}"><strong>${esc(d.label)} ${esc(e.acknowledgement_id)}</strong><p>${e.row_count} rows: ${esc(e.source_record_ids.join(', '))} · snapshot version ${e.snapshot_version} · ${esc(d.selection)}</p><details><summary>Exact prepared export scope, source revisions and server acknowledgment</summary><pre tabindex="0">${esc(JSON.stringify(d.receipt,null,2))}</pre></details><p>Server export acknowledgment only. Client download completion is not established by this receipt. No target import receipt or new authorization.</p></article>`;}).join(''):'No JSON draft has been downloaded in this process.';
  $('model-validation').innerHTML='<thead><tr><th>Check category</th><th>Field</th><th>Evidence / rejection</th></tr></thead><tbody>'+validationEvidence(state.stored_model,p).map(x=>`<tr><td>${esc(x.category)}</td><th>${esc(x.field)}</th><td>${esc(x.code)}<p>${esc(x.explanation)}</p>${Object.hasOwn(x,'expected')?`<p>Source-supported expected: ${esc(JSON.stringify(x.expected))}</p><p>Raw model value: ${esc(JSON.stringify(x.actual))}</p>`:''}</td></tr>`).join('')+'</tbody>';
  $('model-status').textContent=state.stored_model.status+' · '+(state.stored_model.meaning??'Stored output remains unreviewed');$('model-raw').textContent=state.stored_model.raw??'No stored output for this source fingerprint.';
  $('history').innerHTML=state.receipts.map(x=>`<div class="receipt-card ${x.current?'':'historical'}"><strong>${x.current?'Current':'Historical'} normalization receipt ${esc(x.receipt_id)}</strong><p>${esc(x.source_record_id)} · source revision ${esc(x.source_ref.source_revision)} · proposal r${x.proposal_revision}</p><p>${esc(x.proposal_sha256)}</p></div>`).join('')+state.returns.map(x=>`<p>${esc(x.kind)} ${esc(x.source_record_id)}: ${esc(x.reason)} · acceptance not carried forward</p>`).join('');$('experiment').textContent=state.experiment.status+' · live runtime model calls 0 · independent comparison artifacts are separate';controls();
}
function action(path,body={},focus=null){const expected=state?.version;const originFocus=focusGeneration;focus??=document.activeElement.id?{selector:'#'+document.activeElement.id}:null;tail=tail.then(async()=>{busy=true;controls();try{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,expected_version:expected})});const data=await response.json();if(!response.ok){if(data.state)render(data.state);$('message').textContent=(data.error??'ERROR')+': '+data.message;return;}render(data);$('message').textContent='';if(data.download){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(data.download,null,2)],{type:'application/json'}));a.href=url;a.download='reviewed-normalization-draft.json';a.click();URL.revokeObjectURL(url);}}catch(e){$('message').textContent='REQUEST_FAILED: '+e.message;}finally{busy=false;controls();if(focus&&focusGeneration===originFocus&&document.activeElement===document.body)document.querySelector(focus.selector)?.focus();}});return tail;}
async function refresh(){const originFocus=focusGeneration,active=document.activeElement.id;tail=tail.then(async()=>{busy=true;controls();try{const r=await fetch('/api/state'),data=await r.json();if(!r.ok)throw Error(data.message);render(data);$('message').textContent='';}catch(e){$('message').textContent='REQUEST_FAILED: '+e.message;}finally{busy=false;controls();if(active&&focusGeneration===originFocus&&document.activeElement===document.body)$(active)?.focus();}});return tail;}
$('refresh').onclick=refresh;$('site').onchange=()=>action('/api/filter',{site:$('site').value});$('inspected').onchange=controls;
$('review').onclick=()=>action('/api/review',{...binding(),inspected:$('inspected').checked});$('regenerate').onclick=()=>action('/api/regenerate',binding());$('return').onclick=()=>action('/api/return',{...binding(),reason:$('reason').value});
$('correct').onclick=()=>{try{action('/api/correct',{...binding(),reason:$('reason').value,normalized_fields:JSON.parse($('correction').value)});}catch(e){$('message').textContent='INVALID_JSON: '+e.message;}};
$('source-change').onclick=()=>action('/api/source-change',{...binding(),revision:$('revision').value,column:$('changed-column').value,value:$('changed-value').value});
$('export').onclick=()=>action('/api/export',{scope_sha256:state.export_preview.scope_sha256,source_record_ids:[...state.selected]});
$('inspect-model').onclick=()=>{$('correction').value=JSON.stringify(state.stored_model.candidate.normalized_fields,null,2);$('correction').closest('details').open=true;$('inspected').checked=false;$('correction').focus();$('message').textContent='Stored model fields copied for inspection only. No acceptance recorded.';controls();};
$('correction').oninput=()=>{$('inspected').checked=false;$('message').textContent=editorMatches()?'Source-supported editor values. Inspect again before acceptance.':'Unsaved or unsupported candidate: acceptance disabled. Restore or validate source-supported values.';controls();};
$('restore-rule').onclick=()=>{$('correction').value=JSON.stringify(state.proposal.normalized_fields,null,2);$('inspected').checked=false;$('message').textContent='Explicit-rule fields restored in the editor. Fresh inspection is required; no acceptance recorded.';$('correction').closest('details').open=true;$('correction').focus();controls();};
await refresh();
