"""Actual CPU Chrome checks. Original development/stored outputs and synthetic UI responses only."""
import asyncio,json,os,subprocess,urllib.request
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parent
async def ready(origin):
    for _ in range(40):
        try:urllib.request.urlopen(origin,timeout=1).close();return
        except Exception:await asyncio.sleep(.1)
    raise RuntimeError('Owned CPU server did not start')
async def main():
    out=ROOT/'artifacts/ui-refit';out.mkdir(exist_ok=True);media=out;checks={};errors=[];frames=out/'frames';frames.mkdir(exist_ok=True);shots=[]
    for old in frames.glob('frame-*.png'):old.unlink()
    async def shot(page,name,mobile=False):
        await page.screenshot(path=str(media/(name+'.png')),full_page=False)
        shots.append(name+'.png')
        if not mobile:
            for _ in range(4):
                await page.screenshot(path=str(frames/('frame-%04d.png'%len(list(frames.glob('frame-*.png'))))));await asyncio.sleep(.5)
    v2=subprocess.Popen(['node','review-ui/server.mjs'],cwd=ROOT,env=dict(os.environ,P09_V2_PORT='5198'),stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    v1=subprocess.Popen(['node','ui/reference-layout/server.mjs'],cwd=ROOT,env=dict(os.environ,P09_REFIT_PORT='5199'),stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    try:
        await ready('http://127.0.0.1:5198');await ready('http://127.0.0.1:5199')
        async with async_playwright()as p:
            browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',args=['--no-sandbox','--disable-gpu']);context=await browser.new_context(viewport={'width':1440,'height':1100},accept_downloads=True);page=await context.new_page();page.on('pageerror',lambda e:errors.append(str(e)))
            origin='http://127.0.0.1:5198';await page.goto(origin);await page.locator('[data-id=PM001]').focus();await page.keyboard.press('Tab');await expect(page.locator('[data-id=PM002]')).to_be_focused();await page.keyboard.press('Enter');await expect(page.locator('#status')).to_contain_text('semantic inspection required; no acceptance');await expect(page.locator('[data-id=PM002]')).to_be_focused();checks['v2_actual_tab_enter_focus']=True
            await page.locator('#inspect-source').focus();await page.keyboard.press('Enter');await expect(page.locator('#locator')).to_be_focused();await expect(page.locator('#locator')).to_contain_text('fingerprint');checks['source_pointer_named_keyboard_destination']=True
            await page.locator('[data-id=PM001]').click();await expect(page.locator('#case-title')).to_contain_text('PM001');raw=await page.locator('#raw').inner_text();await page.locator('[data-id=PM001]').click();await expect(page.locator('#raw')).to_have_text(raw);checks['repeated_stored_inspection_no_acceptance']=True
            entered=asyncio.Event();release=asyncio.Event()
            async def delayed(route):
                response=await route.fetch();entered.set();await release.wait();await route.fulfill(response=response)
            await page.route('**/api/case?id=PM001',delayed);await page.locator('[data-id=PM001]').click();await entered.wait();await page.locator('[data-id=PM002]').click();await expect(page.locator('#case-title')).to_contain_text('PM002');await page.locator('#inspect-source').click();release.set();await expect(page.locator('#locator')).to_be_focused();await page.wait_for_timeout(100);await expect(page.locator('#case-title')).to_contain_text('PM002');await expect(page.locator('#locator')).to_be_focused();await page.unroute('**/api/case?id=PM001');checks['delayed_old_read_preserves_new_selection_and_explicit_focus']=True
            source=await(await context.request.get(origin+'/api/case?id=PM001')).json()
            for label in ['failed','incomplete','stale']:
                fixture=json.loads(json.dumps(source))
                if label=='failed':fixture.update(attempt_status='failed-attempt',raw_model_content=None,raw_proposal=None)
                elif label=='incomplete':fixture.update(attempt_status='incomplete-output',raw_model_content='{"decision":"propose"}',raw_proposal=None)
                else:fixture['case']['source_fingerprint']='b'*64;fixture['backend']['source_fingerprint']='b'*64
                async def synthetic(route,request):await route.fulfill(status=200,content_type='application/json',body=json.dumps(fixture))
                await page.route('**/api/case?id=PM001',synthetic);await page.locator('[data-id=PM001]').click();await expect(page.locator('#status')).to_contain_text('no reviewable suggestion');await expect(page.locator('#state')).to_contain_text({'failed':'FAILED_ATTEMPT','incomplete':'INCOMPLETE_OUTPUT','stale':'STALE_OR_MISMATCHED_SOURCE'}[label]);checks['synthetic_'+label+'_honest_nonreviewable_state']=True
                if label=='incomplete':await expect(page.locator('#raw')).to_have_text('{"decision":"propose"}')
                if label=='failed':assert 'Not attempted'not in await page.locator('#raw').inner_text()
                await page.unroute('**/api/case?id=PM001')
            await page.locator('[data-id=PM001]').click();await expect(page.locator('#state')).to_have_text('STRUCTURALLY_VALID_REQUIRES_SEMANTIC_REVIEW');await shot(page,'08-v2-semantic-review');await page.locator('[data-id=PM002]').click();await expect(page.locator('#case-title')).to_contain_text('PM002');await shot(page,'09-v2-operating-hour');assert len(await page.locator('.comparison>section').all())==2
            mobile=await browser.new_page(viewport={'width':390,'height':844});await mobile.goto(origin);await mobile.locator('[data-id=PM010]').click();await expect(mobile.locator('#state')).to_have_text('STRUCTURALLY_VALID_REQUIRES_SEMANTIC_REVIEW');assert await mobile.evaluate('document.documentElement.scrollWidth')==390
            minimum=await mobile.evaluate("Math.min(...[...document.querySelectorAll('p,button,pre,blockquote')].filter(el=>el.getBoundingClientRect().width&&el.textContent.trim()).map(el=>parseFloat(getComputedStyle(el).fontSize)))");assert minimum>=14;await shot(mobile,'10-mobile-390',True);assert await mobile.locator('h1').inner_text()=='저장 제안 의미 검토';assert await mobile.locator('h1').evaluate('el=>el.scrollWidth<=el.clientWidth');checks['v2_mobile']={'viewport':390,'document_width':390,'minimum_meaningful_text_px':minimum};await mobile.close()
            origin='http://127.0.0.1:5199';await page.goto(origin);await expect(page.locator('#counts')).to_contain_text('15 admitted captures');await shot(page,'01-source-selection');assert await page.locator('h1').inner_text()=='정비 계획 초안 검토';assert await page.locator('.comparison').first.evaluate('el=>{let a=el.children[0].getBoundingClientRect(),b=el.children[1].getBoundingClientRect();return Math.abs(a.width-b.width)<1&&a.y===b.y}') ;await page.locator('#site').select_option('PLANT-A');await expect(page.locator('#site')).to_be_enabled();await page.locator('[data-select="PM001"]').focus();await page.keyboard.press('Tab');await expect(page.locator('[data-open="PM001"]')).to_be_focused();await page.keyboard.press('Enter');await expect(page.locator('#opened-title')).to_contain_text('PM001');await expect(page.locator('[data-open="PM001"]')).to_be_focused();await page.locator('[data-cell=frequency_text]').click();await expect(page.locator('#cell-detail')).to_be_focused();await shot(page,'02-exact-source-cell');await page.locator('#inspected').check();await page.locator('#review').click();await expect(page.locator('#receipt')).to_contain_text('current accepted');await page.evaluate('scrollTo(0,0)');await shot(page,'03-accepted-normalization');await page.locator('#review').click();s=await(await context.request.get(origin+'/api/state')).json();assert len(s['receipts'])==1;checks['default_keyboard_and_repeated_review']=True
            await page.locator('[data-select="PM001"]').check();await expect(page.locator('#export-rows')).to_have_text('Exact capture IDs: PM001')
            async with page.expect_download()as d:await page.locator('#export').click()
            draft=json.loads(Path(await(await d.value).path()).read_text());assert draft['source_record_ids']==['PM001']and draft['row_count']==1 and draft['target_import_receipt']is None;await expect(page.locator('#export-history')).to_contain_text('snapshot version');await expect(page.locator('#export-history')).to_contain_text('source/review bindings still current');s=await(await context.request.get(origin+'/api/state')).json();ack=s['exports'][0];assert ack['scope_rows'][0]['source_ref']['source_revision']=='A';checks['exact_scope_and_visible_bound_download_ack']=True;await page.locator('#export-panel').scroll_into_view_if_needed();await shot(page,'05-exact-export-scope')
            await page.locator('[data-open="PM003"]').click();await expect(page.locator('#model-validation')).to_contain_text('UNSUPPORTED_NORMALIZED_FIELDS');await expect(page.locator('#model-validation')).to_contain_text('frequency');await expect(page.locator('#model-validation')).to_contain_text('Raw model value:');checks['actual_stored_rejection_field_evidence']=True;await page.locator('#stored-panel').scroll_into_view_if_needed();await shot(page,'06-stored-rejection-fields')
            await page.locator('#changed-column').evaluate("el=>el.closest('details').open=true");await page.locator('#changed-value').fill('매월');await page.locator('#source-change').click();await expect(page.locator('#source-heading')).to_contain_text('PM003 · revision A-demo-2');await expect(page.locator('#model-status')).to_contain_text('Historical stored output; original source revision A');await expect(page.locator('#model-raw')).not_to_have_text('No stored output for this source fingerprint.');assert await page.locator('#inspect-model').is_disabled();await expect(page.locator('#frequency-summary')).to_contain_text('calendar month');checks['current_header_and_historical_model_original_revision']=True;await page.evaluate('scrollTo(0,0)');await shot(page,'07-current-and-historical-revision')
            await page.locator('[data-open="PM001"]').click();await page.locator('#changed-column').evaluate("el=>el.closest('details').open=true");await page.locator('#changed-column').select_option('site');await page.locator('#changed-value').fill('PLANT-B');await page.locator('#source-change').click();await expect(page.locator('[data-open="PM001"]')).to_have_count(0);await expect(page.locator('#export-count')).to_have_text('0 selected rows');await expect(page.locator('#export-history')).to_contain_text('Historical export prepared/acknowledged');s=await(await context.request.get(origin+'/api/state')).json();visible=[r['source_record_id']for r in s['rows']];assert s['opened']in visible and all(i in visible for i in s['selected']);assert s['exports'][0]['scope_rows']==ack['scope_rows'];assert s['exports'][0]['source_reviews_current']is False;assert await page.locator('#export').is_disabled();checks['source_change_reconciles_filter_and_preserves_historical_export']=True;await page.locator('[data-open=PM011]').click();await expect(page.locator('#proposal-status')).to_contain_text('BLOCKED');await page.evaluate('scrollTo(0,0)');await shot(page,'04-ambiguous-trigger-blocked');await page.locator('[data-open=PM002]').click();await expect(page.locator('#proposal-status')).to_contain_text('NORMALIZATION')
            # A second client replaces the currently inspected proposal; the old click must fail.
            await page.locator('#inspected').check();s=await(await context.request.get(origin+'/api/state')).json();b={k:s['proposal'][k]for k in ['source_record_id','source_fingerprint','proposal_sha256','normalized_content_sha256']};r=await context.request.post(origin+'/api/regenerate',data={'expected_version':s['version'],**b});assert r.status==200;await page.locator('#review').click();await expect(page.locator('#message')).to_contain_text('STALE_CLIENT_STATE');assert not await page.locator('#inspected').is_checked();checks['two_client_stale_review_no_reacceptance']=True
            mobile=await browser.new_page(viewport={'width':390,'height':844});await mobile.goto(origin);await expect(mobile.locator('#counts')).to_contain_text('15 admitted captures');assert await mobile.evaluate('document.documentElement.scrollWidth')==390;assert await mobile.locator('h1').evaluate('el=>el.scrollWidth<=el.clientWidth');checks['main_mobile_390_no_clipping']=True;await mobile.close();await context.close();await browser.close()
        assert not errors
        subprocess.run(['ffmpeg','-y','-framerate','2','-i',str(frames/'frame-%04d.png'),'-vf','scale=1280:-2','-c:v','libx264','-pix_fmt','yuv420p',str(out/'review-workflow.mp4')],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
        import hashlib
        assets=[{'path':'artifacts/ui-refit/'+p.name,'bytes':p.stat().st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}for p in out.iterdir()if p.suffix in ['.png','.mp4']]
        (out/'asset-provenance.json').write_text(json.dumps({'kind':'Actual native Chrome CPU workflow, new reference presentation','additional_model_calls':0,'challenge_contents_used':False,'source':'unchanged original public fictional packet and stored outputs; synthetic response states only in checks','assets':assets},indent=2)+'\n')
        (out/'browser-checks.json').write_text(json.dumps({'kind':'Actual CPU Chrome maintenance checks; synthetic response states explicitly named','additional_model_calls':0,'challenge_contents_used':False,'executed_in_CI':False,'screenshots':shots,'checks':checks,'page_errors':errors},indent=2)+'\n');print(json.dumps(checks))
    finally:
        for server in [v2,v1]:server.terminate();server.wait(timeout=5)
if __name__=='__main__':asyncio.run(main())
