"""Actual CPU browser recording. Automated fictional inspection, not SME acceptance."""
import asyncio,json,subprocess,os
from pathlib import Path
from playwright.async_api import async_playwright,expect
ROOT=Path(__file__).resolve().parent;URL='http://127.0.0.1:5089'
async def main():
    os.environ['PLAYWRIGHT_BROWSERS_PATH']=str(ROOT/'private/browser-runtime')
    async with async_playwright() as p:
        browser=await p.chromium.launch(executable_path='/usr/bin/google-chrome',headless=True,args=['--no-sandbox','--disable-gpu']);context=await browser.new_context(viewport={'width':1440,'height':900},record_video_dir=str(ROOT/'private/packet-video'),record_video_size={'width':1440,'height':900},accept_downloads=True);page=await context.new_page();await page.goto(URL);await expect(page.locator('#counts')).to_contain_text('15 admitted captures');await page.wait_for_timeout(1200)
        await page.locator('[data-open="PM004"]').click();await expect(page.locator('#opened-title')).to_contain_text('PM004');await page.locator('#opened-title').scroll_into_view_if_needed();await page.wait_for_timeout(1200)
        await page.locator('[data-cell="frequency_text"]').click();await expect(page.locator('#cell-detail')).to_contain_text('lexical_span');await page.locator('#cell-detail').scroll_into_view_if_needed();await page.wait_for_timeout(1200)
        await page.locator('#model-status').scroll_into_view_if_needed();await expect(page.locator('#model-status')).to_contain_text('REJECTED_BY_RULES');await page.wait_for_timeout(1200);await page.locator('#inspect-model').click();await page.locator('#correction').scroll_into_view_if_needed();await page.wait_for_timeout(1200)
        await page.locator('#inspected').check();assert await page.locator('#review').is_disabled();await page.locator('#reason').fill('Restore the source-supported three-month interval');await page.locator('#correct').click();await expect(page.locator('#message')).to_contain_text('not supported');await page.locator('#message').scroll_into_view_if_needed();await page.wait_for_timeout(1200)
        await page.locator('#restore-rule').click();await page.locator('#correct').click();await expect(page.locator('#binding')).to_contain_text('proposal r2');await page.locator('#inspected').check();await page.locator('#review').click();await expect(page.locator('#proposal-status')).to_have_text('ACCEPTED NORMALIZATION');await page.locator('#receipt').scroll_into_view_if_needed();await page.wait_for_timeout(1200)
        await page.locator('[data-select="PM004"]').check();await page.locator('#export-count').scroll_into_view_if_needed();await expect(page.locator('#export-rows')).to_have_text('Exact capture IDs: PM004');await page.wait_for_timeout(1200)
        async with page.expect_download() as d:await page.locator('#export').click()
        download=await d.value;await download.save_as(ROOT/'private/packet-video-draft.json');draft=json.loads((ROOT/'private/packet-video-draft.json').read_text());assert draft['row_count']==1 and draft['target_import_receipt'] is None
        await page.locator('#site').select_option('PLANT-B');await page.locator('#export-count').scroll_into_view_if_needed();await expect(page.locator('#export-count')).to_have_text('0 selected rows');await page.wait_for_timeout(1200)
        await page.locator('#site').select_option('ALL');await page.locator('[data-open="PM004"]').click();details=page.locator('details').filter(has=page.locator('#revision'));await details.locator('summary').click();await page.locator('#revision').fill('A-video-2');await page.locator('#changed-value').fill('매월');await page.locator('#source-change').click();await expect(page.locator('#model-status')).to_contain_text('ARCHIVED_STALE');await page.locator('#model-status').scroll_into_view_if_needed();await page.wait_for_timeout(1500)
        video=page.video;await context.close();source=await video.path();await browser.close()
    output=ROOT/'artifacts/media/packet-review.mp4';subprocess.run(['ffmpeg','-y','-i',source,'-an','-c:v','libx264','-preset','veryfast','-crf','24','-pix_fmt','yuv420p','-movflags','+faststart',str(output)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    duration=float(subprocess.check_output(['ffprobe','-v','error','-show_entries','format=duration','-of','default=noprint_wrappers=1:nokey=1',str(output)],text=True));assert duration>10
    (ROOT/'artifacts/packet-video-provenance.json').write_text(json.dumps({'kind':'Actual CPU-rendered installed Chrome screen recording','size':[1440,900],'duration_seconds':duration,'encoding':'software libx264','additional_inference_calls':0,'stored_model_attempts':'Earlier frozen twelve-call batch; all rejected by rule gate','human_review':'Automated fictional UI inspection, not independent human maintenance adjudication','demonstrated':['immutable source and exact frequency cell span','stored model rejection','unsupported editor acceptance disabled','source-supported restore plus fresh inspection','exact one-row JSON export, no target receipt','filter clears hidden selection','changed source archives model and review']},indent=2)+'\n')
if __name__=='__main__':asyncio.run(main())
