const $=id=>document.getElementById(id),MAX_BYTES=1024*1024,api='/source-desk/api/';
let state=null,busy=false,tail=Promise.resolve(),retainedSourceText=null;
const example='row_id\tequipment_id\torganization\tsite\ttask_text\tfrequency\tresponsible_role\nlocal-1\t00017\tSYNTHETIC-ORG\tSYNTHETIC-SITE\tReview fictional register labels\tMonthly\tPlanning reviewer\n';
const text=(tag,value)=>{const node=document.createElement(tag);node.textContent=String(value??'');return node;};
function controls(){for(const n of document.querySelectorAll('button,input,select,textarea'))n.disabled=busy;const p=state?.proposal;$('review').disabled=busy||!p||!!p.conflicts.length||!$('inspected').checked;$('prepare-revision').disabled=busy||!p;$('export').disabled=busy||!state?.receipts.some(r=>r.current);}
function render(next){const prior=state?.proposal?.proposal_fingerprint;state=next;const p=state.proposal;if(prior!==p?.proposal_fingerprint)$('inspected').checked=false;
  $('source-counts').textContent=`${state.sources.length}개 원문 이력 · ${state.rows.length}개 현재 행 · 서버 재시작 전까지 유지`;
  $('source-rows').replaceChildren(...state.rows.map(row=>{const tr=document.createElement('tr'),key=JSON.parse(row.key);if(row.key===state.selected)tr.className='selected';for(const v of [`${key[0]} / ${row.source_id} / ${key[3]}`,row.row_id,row.equipment_id,row.site])tr.append(text('td',v));const td=document.createElement('td'),button=text('button','이 행의 근거 열기');button.onclick=()=>action('select',{key:row.key});td.append(button);tr.append(td);return tr;}));
  $('source-history').replaceChildren(...state.sources.map(s=>{const d=document.createElement('details');d.append(text('summary',`${s.admitted?'현재 등록':'보존 이력'} · ${s.namespace} / ${s.source_id} / ${s.source_revision}`),text('p',`SHA-256 ${s.file_hash}`),text('pre',s.text));return d;}));
  $('proposal-status').textContent=p?`${p.status} · ${p.source_id} / ${p.source_revision} / ${p.row_locator}`:'현재 원본에는 검토할 행이 없습니다.';$('source-binding').textContent=p?`원문 SHA-256 ${p.file_hash} · 제안 SHA-256 ${p.proposal_fingerprint}`:'';
  $('source-cells').replaceChildren(...Object.entries(p?.fields??{}).map(([name,field])=>{const tr=document.createElement('tr');tr.append(text('th',name),text('td',field.value===null?'[셀 없음]':field.value===''?'[빈 문자열]':field.value),text('td',field.source_cells.map(c=>`${c.locator} · UTF-8 [${c.span.utf8_start}, ${c.span.utf8_end}) · 원문 ${JSON.stringify(c.span.raw)}`).join('\n')||'원본 근거 없음'));return tr;}));
  $('proposal-evidence').textContent=JSON.stringify(p?{trigger:p.trigger,normalization_rule:p.normalization_rule,unresolved:p.unresolved,conflicts:p.conflicts}:null,null,2);
  const receipt=state.receipts.find(r=>r.current);$('current-receipt').textContent=receipt?`${receipt.receipt_id} · ${receipt.draft.status} · 현재 표시된 제안의 검토 기록`:'현재 제안의 검토 기록 없음';$('review-history').textContent=JSON.stringify({receipts:state.receipts,exports:state.exports},null,2);controls();
}
function action(route,body){const expected=state?.version;tail=tail.then(async()=>{busy=true;controls();try{const response=await fetch(api+route,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,expected_version:expected})}),data=await response.json();if(!response.ok){if(data.state)render(data.state);throw Error((data.error??'ERROR')+': '+data.message);}render(data);$('message').textContent=route==='source'?'원문 등록 완료. 근거 셀을 확인한 뒤 검토를 기록하세요.':'';if(data.download){const url=URL.createObjectURL(new Blob([JSON.stringify(data.download,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='local-reviewed-source-draft.json';a.click();URL.revokeObjectURL(url);}}catch(e){$('message').textContent=e.message;}finally{busy=false;controls();}});return tail;}
function refresh(){tail=tail.then(async()=>{busy=true;controls();try{const response=await fetch(api+'state');if(!response.ok)throw Error('상태를 읽을 수 없습니다.');render(await response.json());$('message').textContent='';}catch(e){$('message').textContent=e.message;}finally{busy=false;controls();}});return tail;}
$('source-form').onsubmit=event=>{event.preventDefault();const source={source_id:$('source-id').value,namespace:$('namespace').value,source_revision:$('source-revision').value,format:$('source-format').value,text:retainedSourceText??$('source-text').value};if(new TextEncoder().encode(source.text).length>MAX_BYTES){$('message').textContent='원문은 UTF-8 기준 1 MiB 이하여야 합니다.';return;}action('source',{source});};
$('source-text').oninput=()=>{retainedSourceText=null;$('file-status').textContent='편집된 텍스트를 등록합니다. SHA-256과 바이트 범위는 등록한 UTF-8 텍스트 기준입니다.';};
$('source-example').onclick=()=>{retainedSourceText=null;$('source-id').value='my-synthetic-source';$('namespace').value='synthetic-local';$('source-revision').value='r1';$('source-format').value='tsv';$('source-text').value=example;$('source-file').value='';$('file-status').textContent='합성 예제를 편집기에 채웠습니다. 아직 등록하지 않았습니다.';};
$('source-file').onchange=async()=>{const file=$('source-file').files[0];if(!file)return;retainedSourceText=null;busy=true;controls();try{const extension=/\.(tsv|json)$/i.exec(file.name);if(!extension)throw Error('.tsv 또는 .json 파일만 허용합니다.');if(file.size>MAX_BYTES)throw Error('파일은 1 MiB 이하여야 합니다.');const raw=new TextDecoder('utf-8',{fatal:true,ignoreBOM:true}).decode(await file.arrayBuffer());$('source-format').value=extension[1].toLowerCase();$('source-text').value=raw;retainedSourceText=raw;$('file-status').textContent=`${file.name} · ${file.size}바이트 · 수정하지 않으면 파일 줄바꿈을 그대로 보존합니다. 등록 버튼을 눌러야 입력됩니다.`;$('message').textContent='';}catch(e){$('source-file').value='';$('message').textContent=e.message;}finally{busy=false;controls();}};
$('prepare-revision').onclick=()=>{const p=state.proposal,s=state.sources.find(s=>s.namespace===p.namespace&&s.source_id===p.source_id&&s.source_revision===p.source_revision&&s.file_hash===p.file_hash);$('source-id').value=s.source_id;$('namespace').value=s.namespace;$('source-format').value=s.format;$('source-text').value=s.text;retainedSourceText=s.text;$('source-revision').value='';$('source-file').value='';$('file-status').textContent='현재 원문을 복사했습니다. 새 버전과 수정 내용을 명시한 뒤 등록하세요.';$('message').textContent='원본은 변경되지 않았습니다. 새 버전 입력은 아직 등록되지 않았습니다.';$('source-revision').focus();};
$('inspected').onchange=controls;$('review').onclick=()=>{const p=state.proposal;action('review',{proposal_fingerprint:p.proposal_fingerprint,file_hash:p.file_hash,source_revision:p.source_revision,row_locator:p.row_locator,inspected:$('inspected').checked});};$('export').onclick=()=>action('export',{proposal_fingerprint:state.proposal.proposal_fingerprint});$('refresh').onclick=refresh;
await refresh();
